on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      artifact_dir:
        required: false
        type: string
        default: "artifact"
      project_version:
        required: true
        type: string
      store_app_id:
        required: true
        type: string
      store_architectures:
        required: false
        type: string
        default: >-
          ["X64", "ARM64"]
    secrets:
      azure_client_id:
        required: true
      azure_client_secret:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      store_seller_id:
        required: true

jobs:
  deploy_store_job:
    runs-on: ubuntu-latest
    steps:
      
      - name: debug_vars
        shell: pwsh
        run: |
          Write-Host "artifact_name: ${{ inputs.artifact_name }}"
          Write-Host "artifact_dir: ${{ inputs.artifact_dir }}"

      - name: artifact_download
        uses: actions/download-artifact@v8
        with:
          name: "${{ inputs.artifact_name }}"
          path: "${{ inputs.artifact_dir }}"

      - name: debug_artifact_dir
        continue-on-error: true
        shell: pwsh
        working-directory: "./${{ inputs.artifact_dir }}"
        run: |
          Get-ChildItem -Recurse

      # - name: Find MSIX file path
      #   id: msix
      #   run: |
      #     $file = Get-ChildItem -Path ${{ env.ARTIFACT_DIRECTORY }} -Filter *.msixupload | Select-Object -First 1
      #     echo "msix_path=$($file.FullName)" >> $env:GITHUB_ENV
      #   shell: pwsh

      # - name: Debug MSIX file path
      #   run: |
      #     echo ${{ env.msix_path }}

      - name: store_setup
        uses: microsoft/microsoft-store-apppublisher@v1.4

      - name: store_configure
        env:
          STORE_SELLER_ID: ${{ secrets.store_seller_id }}
          STORE_TENANT_ID: ${{ secrets.azure_tenant_id }}
          STORE_CLIENT_ID: ${{ secrets.azure_client_id }}
          STORE_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
        run: >-
          msstore reconfigure
          --tenantId "$STORE_TENANT_ID"
          --sellerId "$STORE_SELLER_ID"
          --clientId "$STORE_CLIENT_ID"
          --clientSecret "$STORE_CLIENT_SECRET"

      # https://github.com/jirimaier/DataPlotter/blob/main/.github/workflows/deploy-microsoft-store.yml
      # To submit a local package file instead of a URL, use `msstore publish <path>`.
      # https://github.com/microsoft/PowerToys/blob/main/.github/workflows/msstore-submissions.yml
      - name: store_draft_submission
        env:
          STORE_PRODUCT_ID: ${{ inputs.store_app_id }}
          PRODUCT_UPDATE: >-
            {
              "packages": [
                {
                  "packageUrl": "${{ inputs.artifact_dir }}",
                  "languages": ["en"],
                  "architectures": ${{ inputs.store_architectures }},
                  "isSilentInstall": true
                }
              ]
            }
        run: msstore submission update "$STORE_PRODUCT_ID" "$PRODUCT_UPDATE"

      - name: store_publish_submission
        env:
          STORE_PRODUCT_ID: ${{ inputs.store_app_id }}
        run: msstore submission publish "$STORE_PRODUCT_ID"

      - uses: softprops/action-gh-release@v3
        name: add_release        
        with:
          tag_name: "${{ inputs.project_version }}"